In [32]:
import numpy as np
import pandas as pd

data = {
    'Umur': np.random.normal(loc=35, scale=10, size=1000).astype(int).clip(18, 60),
    'Gaji': np.random.lognormal(mean=12, sigma=0.4, size=1000).astype(int).clip(50000, 10000000),
    'Pengalaman': np.random.binomial(n=15, p=0.3, size=1000) + 1,
    'Tingkat Pendidikan': np.random.choice(
        ['SD', 'SMP', 'SMA', 'Sarjana', 'Magister', 'Doktor'],
        size=1000,
        p=[0.05, 0.1, 0.3, 0.4, 0.1, 0.05]
    ),
    'Gender': np.random.choice(
        ['Laki-laki', 'Perempuan'],
        size=1000,
        p=[0.55, 0.45]
    ),
    'Status': np.random.choice(
        ['Belum Menikah', 'Menikah', 'Cerai'],
        size=1000,
        p=[0.4, 0.5, 0.1]
    ),
    'Jumlah Pembelian': np.random.poisson(lam=50, size=1000).clip(1, 1000),
    'Kategori Produk': np.random.choice(
        ['Elektronik', 'Pakaian', 'Furniture', 'Makanan', 'Kesehatan'],
        size=1000,
        p=[0.3, 0.25, 0.2, 0.15, 0.1]
    ),
    'Kepuasan Pelanggan': np.random.choice(
        [1, 2, 3, 4, 5],
        size=1000,
        p=[0.05, 0.1, 0.2, 0.35, 0.3]
    ),
    'Wilayah': np.random.choice(
        ['Jakarta', 'Bandung', 'Bogor', 'Sukabumi', 'Bekasi', 'Depok', 'Tangerang'],
        size=1000,
        p=[0.4, 0.2, 0.1, 0.05, 0.15, 0.05, 0.05]
    )
}

df = pd.DataFrame(data)

print("Contoh Data:")
print(df.head())

print("\nDeskriptif Statistik Numerik:")
print(df.describe())

print("\nDistribusi Kategorikal:")
print("Tingkat Pendidikan:")
print(df['Tingkat Pendidikan'].value_counts())

print("\nGender:")
print(df['Gender'].value_counts())

print("\nStatus:")
print(df['Status'].value_counts())

print("\nKategori Produk:")
print(df['Kategori Produk'].value_counts())

print("\nKepuasan Pelanggan:")
print(df['Kepuasan Pelanggan'].value_counts())

print("\nWilayah:")
print(df['Wilayah'].value_counts())

Contoh Data:
   Umur    Gaji  Pengalaman Tingkat Pendidikan     Gender         Status  \
0    31  272915           6                SMA  Laki-laki        Menikah
1    47   93119           7                SMP  Perempuan  Belum Menikah
2    38  243408           7            Sarjana  Laki-laki  Belum Menikah
3    38  225835           4                 SD  Perempuan  Belum Menikah
4    23  302984           6            Sarjana  Laki-laki        Menikah

   Jumlah Pembelian Kategori Produk  Kepuasan Pelanggan  Wilayah
0                53       Furniture                   4  Bandung
1                38         Makanan                   4  Bandung
2                49         Pakaian                   3  Jakarta
3                49         Pakaian                   1  Jakarta
4                51         Makanan                   1  Bandung

Deskriptif Statistik Numerik:
              Umur         Gaji   Pengalaman  Jumlah Pembelian  \
count  1000.000000    1000.0000  1000.000000       1000.000000
mean     34.780000  174889.1550     5.504000         49.967000
std       9.464839   72892.1438     1.824092          7.119311
min      18.000000   50000.0000     1.000000         27.000000
25%      28.000000  121159.7500     4.000000         45.000000
50%      35.000000  161879.0000     5.000000         50.000000
75%      41.000000  216234.2500     7.000000         54.000000
max      60.000000  687717.0000    12.000000         72.000000

       Kepuasan Pelanggan
count         1000.000000
mean             3.723000
std              1.132057
min              1.000000
25%              3.000000
50%              4.000000
75%              5.000000
max              5.000000

Distribusi Kategorikal:
Tingkat Pendidikan:
Tingkat Pendidikan
Sarjana     397
SMA         327
SMP         107
Magister     79
SD           54
Doktor       36
Name: count, dtype: int64

Gender:
Gender
Laki-laki    568
Perempuan    432
Name: count, dtype: int64

Status:
Status
Menikah          475
Belum Menikah    421
Cerai            104
Name: count, dtype: int64

Kategori Produk:
Kategori Produk
Elektronik    286
Pakaian       247
Furniture     227
Makanan       137
Kesehatan     103
Name: count, dtype: int64

Kepuasan Pelanggan:
Kepuasan Pelanggan
4    353
5    286
3    211
2     98
1     52
Name: count, dtype: int64

Wilayah:
Wilayah
Jakarta      404
Bandung      200
Bekasi       134
Bogor        110
Depok         55
Sukabumi      53
Tangerang     44
Name: count, dtype: int64